// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: dto.proto

package org.sample.protobuf;

public interface DtoMessageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:proto.DtoMessage)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>required string name = 1;</code>
   * @return Whether the name field is set.
   */
  boolean hasName();
  /**
   * <code>required string name = 1;</code>
   * @return The name.
   */
  java.lang.String getName();
  /**
   * <code>required string name = 1;</code>
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>required string lastname = 2;</code>
   * @return Whether the lastname field is set.
   */
  boolean hasLastname();
  /**
   * <code>required string lastname = 2;</code>
   * @return The lastname.
   */
  java.lang.String getLastname();
  /**
   * <code>required string lastname = 2;</code>
   * @return The bytes for lastname.
   */
  com.google.protobuf.ByteString
      getLastnameBytes();

  /**
   * <code>required int32 age = 3;</code>
   * @return Whether the age field is set.
   */
  boolean hasAge();
  /**
   * <code>required int32 age = 3;</code>
   * @return The age.
   */
  int getAge();
}
