// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: dto.proto

package org.sample.protobuf;

public final class DtoProto {
  private DtoProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_DtoMessage_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_proto_DtoMessage_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\tdto.proto\022\005proto\"9\n\nDtoMessage\022\014\n\004name" +
      "\030\001 \002(\t\022\020\n\010lastname\030\002 \002(\t\022\013\n\003age\030\003 \002(\005B!\n" +
      "\023org.sample.protobufB\010DtoProtoP\001"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_proto_DtoMessage_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_proto_DtoMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_proto_DtoMessage_descriptor,
        new java.lang.String[] { "Name", "Lastname", "Age", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
